### ISSUE TITLE
izin nanya tutor

### ISSUE THREAD

**Issue by taufik0910** [utsmannn/Kemana#3]
selamat sore pak usman, terkait beberapa tutorial dev android kotlin yang ada di channel yt  bpk, yang sedang sya ikutin, untuk tutorial app:Kemana ada g pak,, untuk saya coba pelajari step by step nya pak,,

**Comment by utsmannn** [comment]
untuk tutor app ini belum ada mas, pertengahan tahun rencananya saya buat artikel nya karena ada banyak perubahan untuk aplikasi ini.

btw terima kasih ya mas udah ikutin tutor saya di yt
